volumes:
  pg_data:
  static_files:
  media:

services:
  postgres:
    container_name: foodgram-db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: LostKris/foodgram_backend:latest
    container_name: foodgram-backend
    build: ../backend/foodgram
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes:
      - type: volume
        source: static_files 
        target: /app/static/
      - type: volume
        source: media
        target: /app/media/
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        cp -r /app/docs /app/static/backend/docs &&
        cp -r /app/data/_media/* /app/media/ &&
        sleep 5 &&
        python manage.py migrate &&
        python manage.py loaddata data/data.json &&
        gunicorn --bind 0.0.0.0:8000 foodgram.wsgi:application
      "
    restart: unless-stopped

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - type: volume
        source: static_files
        target: /app/result_build/
  nginx:
    container_name: foodgram-proxy
    build: ./gateway
    ports:
      - 80:80
    volumes:
      - static_files:/usr/share/nginx/html/static/
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend
