volumes:
  pg_data:
  static_files:
  media:

services:
  postgres:
    container_name: foodgram-db
    image: postgres
    environment:
      POSTGRES_USER: foodgram
      POSTGRES_PASSWORD: urreipam
      POSTGRES_DB: foodgram
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: LostKris/foodgram_backend:v1
    container_name: foodgram-backend
    build: ../backend/foodgram
    depends_on:
      - postgres
    environment:
      - DB_NAME=foodgram
      - DB_USER=foodgram
      - DB_PASSWORD=urreipam
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - type: volume
        source: static_files 
        target: /app/static/
      - type: volume
        source: media
        target: /app/media/
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        cp -r /app/docs /app/static/backend/docs &&
        sleep 5 &&
        python manage.py migrate &&
        python manage.py loaddata data/data.json &&
        gunicorn --bind 0.0.0.0:8000 foodgram.wsgi:application
      "
    restart: unless-stopped

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - type: volume
        source: static_files
        target: /app/result_build/
  nginx:
    container_name: foodgram-proxy
    build: ./gateway
    ports:
      - 80:80
    volumes:
      - static_files:/usr/share/nginx/html/static/
      - media:/usr/share/nginx/html/media/
    depends_on:
      - backend
