# Generated by Django 5.2 on 2025-05-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0002_initial'),
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_in', to='core_models.recipe', verbose_name='рецепт'),
        ),
    ]
