name: Main Workflow

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with pylint
      run: |
        cd backend/foodgram
        find . -name "*.py" -and -not -wholename "*/migrations/*" | xargs -r flake8
        
  publish_docker:
    runs-on: ubuntu-latest
    needs: linter
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: |
        cd backend/foodgram
        export VERSION=$(git rev-list --count origin/main)
        docker build . --file Dockerfile --tag lostkris/foodgram_backend:$VERSION
        docker push lostkris/foodgram_backend:$VERSION
        docker tag lostkris/foodgram_backend:$VERSION lostkris/foodgram_backend:latest
        docker push lostkris/foodgram_backend:latest
  
